--
-- Table "DEPT"
--
CREATE TABLE "WKSP_VERANOLINK"."DEPT" 
   (	"DEPTNO" NUMBER(2,0), 
	"DNAME" VARCHAR2(14) COLLATE "USING_NLS_COMP", 
	"LOC" VARCHAR2(13) COLLATE "USING_NLS_COMP", 
	 PRIMARY KEY ("DEPTNO")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/